### ISSUE TITLE
Support for KasperskyOS (an immune-based approach to information security)

### ISSUE THREAD

**Issue by erthink** [erthink/libmdbx#106]
Vote here (and briefly describe your project) to extended support of true security by [Kaspersky OS](https://os.kaspersky.com).

**Comment by signupsi** [comment]
i think adding RAFT support will be very good

**Comment by erthink** [comment]
> i think adding RAFT support will be very good
> https://github.com/canonical/raft

RAFT is inapplicable, at least until MDBX becomes a distributed key-value store.

**Comment by signupsi** [comment]
agree,
MDBX read performance is very good 
added ability ( fault tolerant and  distributed )  will make it very successful 
it can become reliable cache for large systems

**Comment by signupsi** [comment]
i am very curious for MithrilDB. and waiting for the release. 
added distributed capability would make it awesome.

**Comment by signupsi** [comment]
ideally i would envision MithrilDB as following in cluster 

write-Endpoint-A1 
read-endpoint-A1
read-endpoint-A2 
read-endpoint-A3

write-Endpoint-B1 
read-endpoint-B1
read-endpoint-B2 
read-endpoint-B3

and offer availability with  replication and load balancing supported by raft or any other mechanism

**Comment by erthink** [comment]
> ideally i would envision MithrilDB as following in cluster
> ...

Seems the 1Hippeus cluster is it, but this project is closed sine 2015.

**Comment by signupsi** [comment]
have you considered Encryption similar to Firebird 
or something better for libmdbx

**Comment by erthink** [comment]
> have you considered Encryption similar to Firebird or something better for libmdbx

Encryption will NOT be implemented in MDBX, as this requires changing the DB format that is fixed.
Encryption will be available in MithrilDB.

**Comment by erthink** [comment]
There is no sign of interest from users and/or the vendor.
