### ISSUE TITLE
Docs: Does mdbx_cursor_put only allow one flag bit?

### ISSUE THREAD

**Issue by snej** [erthink/libmdbx#110]
According to the doc-comments,`mdbx_cursor_put` allows only one flag to be used, while `mdbx_put` and `mdbx_replace` allow multiple flags. Is this correct?

For `mdbx_put`:

    ##  [in] flags      Special options for this operation. This parameter must be
    ##                  set to 0 or by bitwise OR'ing together one or more of the
    ##                  values described here.

For `mdbx_replace`:

    ##  [in] flags          Special options for this operation. This parameter must
    ##                      be set to 0 or by bitwise OR'ing together one or more of
    ##                      the values described in mdbx_put() description above, [...]

For `mdbx_cursor_put`:

    ##  [in] flags     Options for this operation. This parameter
    ##                 must be set to 0 or one of the values described here:

Note `one of`, not `one or more of`.

**Comment by erthink** [comment]
Thanks for reporting, I will fix this flaw in API description.
