### ISSUE TITLE
Need invitation to lobste.rs

### ISSUE THREAD

**Issue by erthink** [erthink/libmdbx#112]
Сould anyone give me invitation to [lobste.rs](https://lobste.rs/)?
As the developer of _libmdbx_, I want to respond to the @myfreeweb's [comment](https://lobste.rs/s/xt82a0/performance_avoid_sqlite_your_next#c_lqxjxi).

**Comment by myfreeweb** [comment]
Sure :)

**Comment by erthink** [comment]
Thanks!

**Comment by erthink** [comment]
Added comment(s):
 - https://lobste.rs/s/xt82a0/performance_avoid_sqlite_your_next#c_75g4lf
