### ISSUE TITLE
Support OS managed temporary database

### ISSUE THREAD

**Issue by Kerollmops** [erthink/libmdbx#113]
Hey!

Do you think it could be possible for libmdbx to be able to use a temporary file managed by the OS? Without a folder (already supported) and no lock file (already supported) but the most important: constructed from a file descriptor instead of a path.

There is plenty of advantages of being able to initialize and use an environement from a raw file descriptor, for example, it allows users to provide a temporary file that is managed by the OS and therefore [automatically deleted by the OS when the program crashes (# Resource Leaking)](https://docs.rs/tempfile/3.1.0/tempfile/fn.tempfile.html#resource-leaking).

Thank you for your time.

**Comment by erthink** [comment]
I apologize for the delay in answering, I was busy.

First we need to clarify the details:
  - "without a folder" is mostly cosmetics feature, i.e. related only to a "decoration" of a files paths.
  - "without a lock file" means the "read-only access from the single process", i.e. this is very different from the naive (alas, and most likely) assumption without knowing the details.

In the continuation of the topic:
 - this feature is done just by the 'tmpfs' support by OS kernel, i.e. on the Linux you got this just by placing DB to the /dev/shm folder.
 - but without `tmpfs` feature from the kernel (Windows, OSX/iOS) this is required enough of a crutches.

**Comment by erthink** [comment]
This is quite difficult to implement while preserving all the features of _libmdbx_.
In addition, (as it seems to me) these are quite rare scenarios, for most of which it is now quite simple to implement (without _libmdbx_ & without reinvent the wheel) via boost::interprocess, i.e. offset_ptr + intrusive containers and/old allocators in a shared memory.

So, for systems without the `tmpfs` support I doubt that such feature is reasonable to be provided.
On the other hand, I will try to take your wishes into account when developing the C++ interface.
For instance, an API to support creating a database with explicit provision of regions of already allocated memory.

**Comment by Kerollmops** [comment]
I think I understand that there is some downsides to make this available in mdbx.

I will give you just a little bit of context, I am working on a brand new search engine that I will shortly integrate into MeiliSearch. This search engine must index the documents the users sends, and as the new CPUs these days aren’t much more faster than the previous years they expose more cores, so, I implemented a parallel indexer that is very very fast (indexing 108m little documents in 15min).

It opens one LMDB environnement by core, wrapping it with an ARC cache (Adaptative Replacement Cache) to avoid looking to much on the disk. Unfortunately there is a downside to that technique, if the process crashes (OOM killed) the LMDB environments are not cleared as the deletion of these folders is managed by the program itself.

So I ended up using my portage of MTBL (SST Table like) data-structure which can be created from any Rust File, therefore a file marked as temporary that the OS is aware of and that will be cleaned in case of a kill or any ctrl-c or signal.

I looked into the LMDB source code to see if it could be at least possible to create a database from simply a file descriptor and what I saw is that the file descriptor is extracted from the path given by the user and only saved. It doesn’t seem to be used again neither for a new memory map or anything except to give it back to the user when it asks for it.

Do I miss something, I believe you probably better know the LMDB codebase than myself, so you are probably more aware of how LMDB uses the path. Would it be possible in anyway to fork LMDB to add a feature where we can open an environment from only a file descriptor?

**Comment by hyc** [comment]
If you want the file to go away on a crash, and don't need multiprocess access, you can simply delete the file after opening it. This works on all POSIX systems, anyway; won't work on Windows.

**Comment by erthink** [comment]
@Kerollmops, could you clarify by choosing one of:

1. The solution suggested by Howard is suitable for you, and this issue could be closed.
2.  Otherwise, the file deletion hack is not suitable and you stiil need something like
`int mdbx_env_open_via_handles(env, flags, int dxb_lazy_handle, int dxb_sync_handle, int lck_handle);`

?

**Comment by Kerollmops** [comment]
Second solution would be better as it would let users choose the way files are created and how.

However I didn't choose any of the solutions above as I [used another key-value store](https://github.com/Kerollmops/oxidized-mtbl) (more of an sorted string table format) that I am able to merge and eventually write (with `append`) into LMDB.

**Comment by erthink** [comment]
OK, then I will close this issue and try to spend more time on MithrilDB, where there will be more features:

1. Support for temporary databases that are accessible from a single process and disappear when closed.

2. Support for temporary databases that are accessible from multiple processes and disappear on rebooted or explicitly deleted.

3. Support for placing database in a custom (user-provided) memory regions.

4. Support for placing the database file on a block device.

5. Support for multi-partition databases with placement on different media.
For example, from three partitions placed on a SSD/NVMe, on a HDD and in the tmpfs.
Technologically:
   - each partition is an independent database, but with a common LCK-file for synchronization and sharing access.
   - while opening sub-database/kv-space (i.e. DBI-handle) the target partition selected by an additional parameter.

Regards.

**Comment by Kerollmops** [comment]
Wow that is awasome, so much interresting features!

> 3. Support for placing database in a custom (user-provided) memory regions.

Does it mean that it would be possible to open and store a database from a `Vec<u8>` or any `void*` for example?

**Comment by erthink** [comment]
> Wow that is awasome, so much interresting features!
> 
> > 1. Support for placing database in a custom (user-provided) memory regions.
> 
> Does it mean that it would be possible to open and store a database from a `Vec<u8>` or any `void*` for example?

Yes, but these should be page-aligned and fairly large (a few dozen pages) regions of shared memory, with sync-to-disk interface. I.e. not just a `Vec<u8>`.

**Comment by erthink** [comment]
For micro-DB (i.e. inside a `Vec<u8>`) you should take look to the [libfptu](https://github.com/PositiveTechnologies/libfptu).
