### ISSUE TITLE
Designing a user-end locking API

### ISSUE THREAD

**Issue by Kerollmops** [erthink/libmdbx#119]
Hi,

I am currently looking at the `NO_LOCK` flag of LMDB/libmdbx, and I opened an issue about that, could you take a quick look at it, please? It would be really helpful to me.

https://github.com/Kerollmops/heed/issues/58

**Comment by erthink** [comment]
Well, I'll look at it now, but it's better to ask such questions in the telegram group https://t.me/libmdbx.

**Comment by erthink** [comment]
As I already wrote, I will try to implement the `mdbx_env_delete()` function today.
