### ISSUE TITLE
mdbx_cursor_get(NEXT/PREV) may fail with MDBX_DB_CORRUPTED after mdbx_cursor_del(MDBX_CURRENT)

### ISSUE THREAD

**Issue by erthink** [erthink/libmdbx#121]
This seems to be another bug inherited from LMDB.
The difference is that libmdbx returns an error, whereas LMDB crashes, returns invalid data, or damages the database.

Thanks @AskAlexSharov for reporting.

**Comment by AskAlexSharov** [comment]
Everything I know about this bug is: 
- it happens on DupSort bucket 
- it happens in loops like: 
```
for cursor.First(); ; cursor.Next() { cursor.DeleteCurrent() } 
```
and method Next sometimes returns DB_CORRUPTION
- LMDB did crush with: 
```
mdb.c:5940: Assertion 'IS_LEAF(mp)' failed in mdb_cursor_next()
```
You can see this line here: https://github.com/ledgerwatch/lmdb-go/blob/master/lmdb/mdb.c

**Comment by hyc** [comment]
Thanks for the ping. Corresponding patch for LMDB is here https://git.openldap.org/openldap/openldap/-/merge_requests/193 but if you have sample code to reproduce the failure, would be nice to see it.
