### ISSUE TITLE
MDBX_GET_BOTH_RANGE behave different from LMDB

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#130]
test case: 
```
// Setup
createDupsortDBI()
put("k1", "v1", UPSERT)
put("k1", "v2", UPSERT)
put("k1", "v3", UPSERT)

// Do call with non-existing key (which is before existing key)
mdb_cursor_get("k0", "v0", GetBothRange)

// LMDB Result
MDB_NOTFOUND

//MDBX Result - returns non-exsting key and first found value
success, "k0", "v1"
```

This is error which I described few days ago as "looks like DBI returning to me keys which I didn't put there" - so, it returns key which I didn't put there but passing to GetBothRange.

Compatibility is not critical for me (if it's known) - but returning non-existing key seems a bug.

**Comment by erthink** [comment]
Confirmed.

**Comment by erthink** [comment]
@AskAlexSharov, thank for reporting.
