### ISSUE TITLE
mdbx_txn_commit_ex: MDBX_KEYEXIST: Key/data pair already exists

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#131]
It's a bit unclear for me - what I can do with MDBX_KEYEXIST inside mdbx_txn_commit_ex
last master: 21d2af9e902ba6e3220651996754427ff9ac361d
do you need some additional info?

**Comment by erthink** [comment]
Hm, I fixed (3fd079262cdc79f302d3b16df30969516174f85b) a similar problem a week ago.
To understand what was going on, I had to add additional logging and run tests on cluster for a weeks.

Anyway I need to understand how you managed to provoke this problem.
It is very likely that will also have to enable additional logging with a special patch.

**Comment by erthink** [comment]
Currently I assume this is a regression since 55d190bad9723fd9766466005b1a14e70779fc89 and 70241e25db0efd7d42a8fb8af2ab552b59e92cc1 for https://github.com/erthink/libmdbx/issues/123.
I.e the problem only affects your extreme use cases and does not appear in others.
If so, it will be easier to fix the problem, although I still need to think about how to do it without new regressions.

**Comment by AskAlexSharov** [comment]
For now it happened 2 times: 1 time on small transaction, 1 time on big one. 
Env had Lifo flag and small freelist (I didn't test without Lifo flag). 
And doesn't reproduce anymore. Let's see if it will reproduce during night tests.

**Comment by erthink** [comment]
In a few hours (as soon as I get to the computer) I will provide you a patch with additional logging.

It will be great if you add code to collect these logs. This log can be stored in memory, cleared at the start of each transaction, and saved only when an error occurs.

**Comment by AskAlexSharov** [comment]
ok, i have way to reproduce it: by dropping DBI. 
logs - no problem to add.

**Comment by erthink** [comment]
[logging-update-gc.patch](https://gist.github.com/erthink/8f5eba3633ffe35e67f84a75361b0ecb)

Don't forget to set your logger via [mdbx_setup_debug()](https://github.com/erthink/libmdbx/blob/21d2af9e902ba6e3220651996754427ff9ac361d/mdbx.h#L822-L827).

**Comment by AskAlexSharov** [comment]
[1.log](https://github.com/erthink/libmdbx/files/5472511/1.log)

**Comment by AskAlexSharov** [comment]
[1.log](https://github.com/erthink/libmdbx/files/5472728/1.log)

**Comment by AskAlexSharov** [comment]
[1.trace.log](https://github.com/erthink/libmdbx/files/5472753/1.trace.log)

[1.trace.log](https://github.com/erthink/libmdbx/files/5472752/1.trace.log)

[1.extra.log](https://github.com/erthink/libmdbx/files/5472750/1.extra.log)

**Comment by erthink** [comment]
С логами пара проблем:
1. Вы использовали отладочную сборку, в которой логирование включено для всего объема кода. Из-за этого логи получились огромными.
2. В использованной отладочной сборке вы также включили внутренний аудит, и судя по логам это выявило расхождение в кол-ве используемых и выделенных страниц БД. Грубо говоря, аудит посчитал что выявил потерю страниц (нигде не учтенные страницы) и коммит был прерван с возвратом `MDBX_PROBLEM` раньше чем дело дошло до `MDBX_KEYEXIST`.

Достаточно маловероятно, что в libmdbx сейчас есть баги приводящие к потере страниц. Исходно даже в LMDB c этим было относительно хорошо, и похоже оставшаяся парочка давно была устранена в libmdbx. Кроме этого, всё это было многократно проверено тестами и практическим использованием в тысячах инсталляций.

А вот с аудитом ситуация обратная - эта внутренняя feature используется только при отладке, в некоторых тестах и "на всякий случай" разбирательстве с проблемами. Т.е. аудит относительно мало обкатан в сравнении с остальным кодом.
Соответственно, похоже что включив аудит вы выявили в нём какой-то логический недочет.

**Поэтому для получения логов по исходной проблеме предлагаю использовать обычную сборку libmdbx, но с предложенным выше патчем. А пока вы готовите логи я поразбираюсь с аудитом.** Если технически вам удобно использовать отладочную сборку, то всё равно стоит приложить патч, а посредством `mdbx_setup_debug(MDBX_LOG_VERBOSE, MDBX_DBG_ASSERT, your_logger)` уменьшить объем логов и (временно) отключить аудит.

**Comment by AskAlexSharov** [comment]
Перестарался. Вот что осталось:
```
mdbx_setup_dxb:13079 open-MADV_DONTNEED 108364316..108394890
mdbx_set_readahead:7697 readahead OFF 0..108364316
mdbx_find_oldest:7616 update oldest 0 -> 167216
```

**Comment by AskAlexSharov** [comment]
А, нет, вот: 
```
check_fstat:26405 lck-file is too short (0), exclusive-lock needed
mdbx_read_header:11788 latch meta[0]
mdbx_read_header:11788 latch meta[1]
mdbx_read_header:11788 latch meta[2]
mdbx_read_header:11788 latch meta[2]
mdbx_setup_dxb:12707 header: root 3/108361938, geo 3/108364316-108364316/536870912 +65535 -1, txn_id 167217, Steady
mdbx_setup_dxb:12833 current boot-id 8254ba6238386bb6-99e6df91350c4905 (available)
mdbx_set_readahead:7697 readahead OFF 0..108364316
mdbx_find_oldest:7616 update oldest 0 -> 167217
mdbx_page_alloc:8485 try growth datafile to 108394890 pages (+30574)
mdbx_mapresize:7772 resize datafile/mapping: present 443860238336 -> 443985469440, limit 2199023255552 -> 2199023255552
```

**Comment by erthink** [comment]
1. У меня получилось воспроизвести вторичную проблему с аудитом (`MDBX_PROBLEM` при коммите) в тестах на больших транзакциях. Это очень похоже на регресс наведенный какими-то последними правками. Сейчас разбираюсь и (предположительно) сегодня поправлю.
2. Чтобы получить лог для устранения исходной проблемы (`MDBX_KEYEXIST`  при коммите) _НУЖНО_ приложить [патч](https://gist.github.com/erthink/8f5eba3633ffe35e67f84a75361b0ecb) и включить логирование без аудита `mdbx_setup_debug(MDBX_LOG_VERBOSE, MDBX_DBG_ASSERT, your_logger)`. Тогда вы увидите небольшие логи, преимущественно с префиксом `mdbx_updata_gc:` - именно они и нужны.
Всё что получилось выше, к сожалению, _совсем_ не содержит требуемой информации.

**Comment by AskAlexSharov** [comment]
[Uploading mdbx_update_gc.log…]()

**Comment by AskAlexSharov** [comment]
[mdbx_update_gc.log](https://github.com/erthink/libmdbx/files/5475745/mdbx_update_gc.log)

**Comment by erthink** [comment]
Похоже обе проблемы являются регрессом после https://github.com/erthink/libmdbx/issues/121.

**Comment by erthink** [comment]
@AskAlexSharov, предположительно проблема связана с трекингом курсоров - когда для одного DBI открыто несколько курсоров, и удаления/вставки, выполняемые через один курсор, должны отображаться на состояние остальных. Под состоянием курсора тут понимается не только "флажки", но и стек страниц дереве с позициями в них.

Похоже что это еще одна унаследованная из LMDB ошибка, которая не проявлялась до исправления https://github.com/erthink/libmdbx/issues/121. Для надежного исправления мне потребуется доработать тесты и тщательно всё перепроверить, на что потребуется до 2 недель.

**Comment by AskAlexSharov** [comment]
Great. If it’s clearly inherited problem, share to Howard your reaults please.

**Comment by AskAlexSharov** [comment]
Faced new (probably with same root-cause problem) on master 21d2af9e902ba6e3220651996754427ff9ac361d :
code like
```
cursor.Last()
for {
   // ... get key, value from sorted list
   cursor.Put(key, value, AppendDup)
}
```
returns error `MDBX_EKEYMISMATCH: The given key value is mismatched to the current cursor position` 
I wonder if cursor must be in "some position" for AppendDup.

**Comment by erthink** [comment]
> I wonder if cursor must be in "some position" for AppendDup.

This is  just a one/common message for error returned in similar cases, i.e. when the key/data don't match the cursor (virtual or implied) position:
- `MDBX_APPENDDUP` = data value must be great than any present duplicate/multivalue for the specified key.
- `MDBX_APPEND` =  key value must be great (or equal for DUPSORT-database) than any key of DBI/sub-database, but no restriction for data value (include DUPSORT-databases).
- `MDBX_APPEND | MDBX_APPENDDUP` = both of above.
- `MDBX_CURRENT` = key must match the current cursor position.

Are you sure that in your case the values for each key are added in ascending order?

**Comment by AskAlexSharov** [comment]
"Are you sure that in your case the values for each key are added in ascending order?" - you are right. I just get used to another error of LMDB in this case. Nevermind then.

**Comment by erthink** [comment]
> У меня получилось воспроизвести вторичную проблему с аудитом (`MDBX_PROBLEM` при коммите) в тестах на больших транзакциях. Это очень похоже на регресс наведенный какими-то последними правками. Сейчас разбираюсь и (предположительно) сегодня поправлю.

Пока хороших новостей нет:
 - Проблема НЕ проявляется с пробными/черновыми исправлениями, однако повторно воспроизвести её и БЕЗ исправлений также НЕ получилось.
- Т.е. в тестах проблема воспроизводится при каком-то достаточно редком стечении обстоятельств, которые пока не удалось выявить и/или формализовать.

**Comment by erthink** [comment]
@AskAlexSharov, если у вас есть более-менее стабильный сценарий воспроизведения, то желательно чтобы вы попробовали ветку [`fix-31`](https://github.com/erthink/libmdbx/tree/fix-131).

**Comment by AskAlexSharov** [comment]
Нет, проблема c audit не воспроизводится на master/fix-131/debug-gc-update

**Comment by erthink** [comment]
Текущее состояние дел:
1. После однократного воспроизведения проблему повторить не удалось. При этом тест был повторен на различных машинах суммарно порядка 10000 раз, с фиксированным random-seed как при однократном воспроизведении.
2. Доработку тестов и связанные с этим исправления я почти завершил и сегодня-завтра пролью эти правки (после завершения тестов и рефакторинга).
3. Доработанные тесты выявили несколько багов/недочетов, но все они вне традиционных сценариев использования и не объясняют замеченную проблему.

**Comment by AskAlexSharov** [comment]
1. Какую именно проблему? MDBX_KEYEXIST или MDBX_PROBLEM? (вторая у меня не воспроизводится, первая вроде воспроизводилась, могу попробовать еще раз). В любом случае готов запускать наши тесты на новой ветке.

**Comment by erthink** [comment]
> 1. Какую именно проблему? MDBX_KEYEXIST или MDBX_PROBLEM? (вторая у меня не воспроизводится, первая у меня воспроизводится при drop 30Gb DupSort DBI). В любом случае готов запускать наши тесты на новой ветке.

`MDBX_PROBLEM` было в ваших логах, когда вместе с отладкой вы включили аудит.
После чего я предположил что это два проявления одной проблемы.

Сейчас я пролью правки в ветку `devel` и вам стоит её попробовать на ваших кейсах, ибо мне удалось воспроизвести проблему только однократно.

**Comment by AskAlexSharov** [comment]
В новом devel 56a52b0b01ca33f317b364417c5cf17846c0d140 при drop 30Gb DupSort DBI: 
`mdbx_txn_commit_ex: MDBX_KEYEXIST: Key/data pair already exists`

**Comment by erthink** [comment]
Видимо мне всё-таки придется скачать вашу тестовую базу и поковыряться локально.
Иначе не понятно как воспроизводить.

**Comment by AskAlexSharov** [comment]
Нет, я ошибся. 

То место которое раньше показывало `MDBX_KEYEXIST: Key/data pair already exists` сейчас показывает `MDBX_TXN_FULL: Transaction has too many dirty pages, i.e transaction is too big`. 

`mdbx_stat -s` - показывает, что тот DBI который я дропаю пуст. Т.е. `MDBX_TXN_FULL` я получаю на транзакции которая делает 2 действия - дропает dbi, создает dbi, commit. 

Но у этой базы большой фрилист: 
[mdb_stat_ff.log](https://github.com/erthink/libmdbx/files/5544384/1.log)

Сейчас попробую убрать LifoReclaim флаг.

**Comment by erthink** [comment]
Хорошо, погоняйте/потестируйте ещё.
Сейчас важно "есть слона частями" - сначала разобраться с `MDBX_KEYEXIST` (основной функционал), а уже после с `MDBX_TXN_FULL` (улучшения).

**Comment by erthink** [comment]
@AskAlexSharov, пожалуйста попробуйте (несколько раз, по-разному и т.п.) воспроизвести проблему на ветке `devel`.
Если не получиться, то будем считать что баг устранен и я займусь `MDBX_TXN_FULL`.

**Comment by AskAlexSharov** [comment]
Да, я запустил жирный тест. Но, он занимает несколько дней, думаю остались сутки до конца. Думаю можно считать что баг устранен,  а о результатах тестов я напишу через день-два.

**Comment by AskAlexSharov** [comment]
Закончил тестирование. Специальных ошибок не возникает - но результат не сходится (в той части приложения где у нас кастомный dcmp). Пока не нашел причины - занимаюсь.

**Comment by erthink** [comment]
Дайте больше информации о расхождениях, я подумаю что может быть.

Кроме этого, после расширения тестов курсоров и соответствующих доработок поведение курсоров стало более унифицированным, но поменялось (см ниже). При этом я стремился не менять поведение и сделать его максимально идентичным LMDB (т.е. так как задумывал Говард Чу). Тем не менее, отличия от LMDB скорее всего есть, но из-за ошибок/недочетов в LMDB (вернуть эти правки проблематично, нужно начинать с тестов).

Исправления поведения курсоров:
 - использование курсора после неудачного поиска, вместо возврата ошибки, могло приводить к падению или получению левых данных.
 - переходы NEXT/PREV могли оставлять курсор в неверном состоянии (похоже на предыдущий случай).

**Comment by erthink** [comment]
Есть ли какая-нибудь новая информация?

**Comment by AskAlexSharov** [comment]
К сожалению, пока проблема возникла 2 раза, но нормально воспроизвести и конкретизировать не удалось.

**Comment by erthink** [comment]
Так в двух словах - какие расхождения вы наблюдаете?
Т.е. что не так?

**Comment by AskAlexSharov** [comment]
Есть часть приложения: 2 курсора - один dupsort без кастомного dcmp, другой dupaort с кастомным dcmp. Курсоры бегут только вперед - иногда next, иногда setRange, иногда setBothRange. Все полученные данные пропускаются через хеш-функцию - вот этот хеш не сошелся. 

Ну, т.е. по пути много чего могло пойти не так.

**Comment by erthink** [comment]
На всякий: 
 - setBothRange требует чтобы ключ был и при его наличии переходит к equal or great значению среди дубликатов.
 - Позиционирование курсоров тестируется как тестами в libmdbx, так и в libfpta. Пока не представляю где тут могут быть проблемы.
 - При удалении или изменении записей в позиции курсора (через другой курсор) могут быть неожиданные эффекты, особенно в случае DUPSORT. Если у вас есть такие сценарии их лучше избежать (напишите при необходимости, я поясню).

**Comment by AskAlexSharov** [comment]
Может быть и нет проблемы, раз не воспроизводится. 

“ При удалении или изменении записей в позиции курсора (через другой курсор) могут быть неожиданные эффекты, особенно в случае DUPSORT. Если у вас есть такие сценарии их лучше избежать (напишите при необходимости, я поясню).” - мы перешли на пары курсоров (один читает, второй удаляет) везде потому-что это тот самый баг lmdb с которого у нас тут все началось :-) я поменяю приложение чтобы оно использовало только 1 курсор на 1 DBI.
