### ISSUE TITLE
Drop DBI: find way to not return MDBX_TXN_FULL

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#133]
Reasoning:
- DB can do Drop more efficient than App. App only can loop over `cursor.First(); cursor.Delete();` and periodically commit.
- DB knows better how manage freelist during Drop DBI - it can break freelist to multiple records, can defrag it, etc...
- DB can maximize IO utilization. 
- If drop of DBI causing too many dirty pages - DB can do something with it (spill?)

This issue is not very important "loop over `cursor.First(); cursor.Delete();` and periodically commit" is fine for me - because this way I can show progress for users (print current key, etc...).

**Comment by erthink** [comment]
The `mdbx_drop()` will be the best way after https://github.com/erthink/libmdbx/issues/128.

**Comment by AskAlexSharov** [comment]
good
