### ISSUE TITLE
commit_ex latencies: most of time is not attributed

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#134]
Example from Mac:
```
preparation=0s gc=20.477295ms audit=0s write=0s fsync=3.055618286s ending="457.764µs" whole=47.268081665s
```

Example from Linux (HDD): 
```
preparation=0s gc=55.831909ms audit=0s write=0s sync=9.498962402s  ending=1.922607ms  whole=14m38.648544312s
```

FYI: we also observing slow commits (minutes) on Mac in LMDB. And trying to understand the reason.

**Comment by erthink** [comment]
The `write=0s` looks suspicious.

But I don't have ideas yet, since the code for latency measuring is quite simple, and the conversion of the time representation has been tested.

**Comment by AskAlexSharov** [comment]
ha, ha, ha. `The write=0s looks suspicious.` - yes, it's bug on my side, will post here new timings tomorrow.

**Comment by AskAlexSharov** [comment]
Linux: 
```
 preparation=0s         gc=0s           audit=0s write=1.126541138s fsync=1.16746521s  ending=0s          whole=2.294021606s
```

Mac:
```
preparation=2.456665ms gc="244.141µs" audit=0s write=1m30.675170898s fsync=2.960205ms ending=0s whole=1m30.680877686s
```
