### ISSUE TITLE
mdbx_txn_begin: 2nd write transaction without MDBX_TXN_TRY flag - returns error instead of block

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#135]
Error:
```
MDBX_BUSY: Another write transaction is running, or environment is already used while opening with MDBX_EXCLUSIVE flag
```

Env opened without flags.
Transactions have only MDBX_TXN_READWRITE flag. 

As I understand - this error must be returned only if MDBX_TXN_TRY flag passed.

**Comment by erthink** [comment]
You seem to be calling "mdbx_txn_begin ()" from the same thread that is already running the write transaction.
In this case you will get the `MDBX_BUSY` error, or deadlock on a mutex otherwise.

**Comment by AskAlexSharov** [comment]
yes, then make sense.
