### ISSUE TITLE
Document that MDBX_INTEGERDUP requires MDBX_DUPFIXED

### ISSUE THREAD

**Issue by snej** [erthink/libmdbx#140]
`mdbx_dbi_open` fails with error `EINVAL` if the flags include `MDBX_INTEGERDUP` but not `MDBX_DUPFIXED`. 

This isn't documented, at least not in the header, and it confused me for a while until I tried various combinations of flags and figured it out. In hindsight this requirement makes sense (the docs do say the integers have to be the same size), so I assume it's a problem with the docs instead of the code.

### Steps to Reproduce

```C
MDBX_txn *txn = /* ...open txn */ ;
MDBX_dbi dbi;
int err = mdbx_dbi_open(txn, "name", MDBX_DUPSORT | MDBX_INTEGERDUP, &dbi);
assert(err == 0);
```

* Expected: Assertion succeeds
* Actual: Assertion fails; err is 22, which is `EINVAL` on macOS.

### Workaround

Add `MDBX_DUPFIXED` to the flags.

**Comment by erthink** [comment]
Thanks you for reporting.
