### ISSUE TITLE
Shouldn't the C functions return MDBX_error_t, not int?

### ISSUE THREAD

**Issue by snej** [erthink/libmdbx#141]
It's great the that C API (mdbx.h) uses enums for most constants now. Since there's an enum for the error codes, `MDBX_error_t`, shouldn't that be used for the return type of the functions that return error codes, instead of `int`?

This improves auto-generated bindings in languages like Nim that don't allow implicit casts between ints and enums. In my current code, the function results have to be explicitly cast to `MDBX_error_t`.

It also makes it clearer from its signature that a function returns an error code. While most of them do, there are some functions returning`int`s that have other interpretations, like `mdbx_txn_flags` and `mdbx_env_get_maxkeysize_ex`.

**Comment by erthink** [comment]
Unfortunately, this is a problem until it is no open enum types for most programming languages, including C++:
- Many functions can also return system error codes, in addition to the predefined libmdbx's errors.
- In other words, the returned error codes can be arbitrary and we can't list them in the enum type definition.
- On the other hand, using a value for an enum type that is not listed in its definition is undefined behavior in many programming languages, including modern C++.

So, returning an arbitrary value from enum-typed function (i.e. casting an arbitrary value to enum type) will lead the undefined behavior, and UBSAN in the current version of CLANG catches such cases.

**Comment by snej** [comment]
Ouch, you're right of course.
