### ISSUE TITLE
need nodejs npm binding

### ISSUE THREAD

**Issue by guozanhua** [erthink/libmdbx#148]

**Comment by erthink** [comment]
PR is welcome!

**Comment by erthink** [comment]
Please use the [new C++ API](https://github.com/erthink/libmdbx/blob/master/mdbx.h%2B%2B) as a basis/template.

**Comment by erichocean** [comment]
There is an existing node-lmdb binding that should be straightforward to port.

**Comment by kriszyp** [comment]
Yes, I made a port of it (well, of lmdb-store that contains node-lmdb) to libmdbx here:
https://github.com/kriszyp/lmdbx-store
Certainly would need some more testing and attention. There a number of issues with the port, some which I mentioned here:
https://github.com/DoctorEvidence/lmdb-store/issues/24

**Comment by anuragvohraec** [comment]
Here is another lib:
https://www.npmjs.com/package/node-mdbx#putkey-value

**Comment by erthink** [comment]
Have a couple of [nodejs bindings](https://github.com/erthink/libmdbx#bindings) for now :)

**Comment by kriszyp** [comment]
@erthink In addition, the latest release of https://github.com/kriszyp/lmdbx-js should now support Deno, which I think counts as a separate platform for libmdbx, in addition to NodeJS.
