### ISSUE TITLE
Inter-Process locking supported?

### ISSUE THREAD

**Issue by Thermi** [erthink/libmdbx#149]
Hi, I'm looking to replace the usage of berkeley db in an application with libmdbx. The application uses the database different processes, so I need to make sure that concurrent access works fine. Does libmdbx support that (interprocess locking)?

**Comment by erthink** [comment]
Oh, yes... Did you read the `README`?
// please, ok?

**Comment by erthink** [comment]
On the other hand, your fresh perspective would reveal shortcomings in the presentation of information (which is quite important).
So i will be grateful to you both for any comments and (even better) for a concrete PR.

// p.s. seems is a friday sunset on my KP time ;))

**Comment by Thermi** [comment]
I did read the `README`, but it only mentioned ``` multi-threaded processes``` not different processes as in processes that do not share the heap.

**Comment by erthink** [comment]
Well.
What differences do you see after reading the documentation, and how do you propose to formulate them?

**Comment by Thermi** [comment]
Yeah well, until I read the code I do not know if libmdbx actually supports inter process locking or just intra process locking. So which of it is it? :P

**Comment by erthink** [comment]
> Yeah well, until I read the code I do not know if libmdbx actually supports inter process locking or just intra process locking. So which of it is it? :P
Well. What differences do you see after reading the documentation, and how do you propose to formulate them?
... Nope....

> EDIT: Okay, after reading the code it seems you use posix file locking or whatever is available on the platform. Just add that to the readme and add a mention that it uses posix file locking or platform equivalent to do that. Smart people will then know directly if it works for their use case or not.

Oh yes, I would (a current) "windows" and something along the way.
Nonetheless if I understand you correctly, you are wrong.
Again, basically: single serialized writer, + a lot of unblocked readers.

**Comment by Thermi** [comment]
I'm not impliying anything about how libmdbx does the locking, just that it uses the posix APIs for that.

**Comment by erthink** [comment]
Well, lets to play?
/
do it.

**Comment by Thermi** [comment]
Sorry, I don't want to have any kind of argument or verbal fight here. I just wanted to know if libmdbx supported inter process locking, which it does.
If you are interested in adding any information to the README, just add which APIs you use to do that and that you support inter process locking, too, so a DB can be read from and written to from different processes without trouble.
