### ISSUE TITLE
MSVC's bug: Building with Visual studio 2019 stuck

### ISSUE THREAD

**Issue by gogolxdong** [erthink/libmdbx#154]
Building with Visual studio 2019 after cmake . stuck at some point.

**Comment by erthink** [comment]
This is MSVC compiler bug, for more info see the https://github.com/erthink/libmdbx/issues/116.

**Comment by erthink** [comment]
Reopen only to stay in the wontfix state and avoid duplicates due to MSVC bugs.

**Comment by MrSmith33** [comment]
When building mdbx myself, I used `Release` build with `/Ob1` switch instead of `/Ob2`.

**Comment by erthink** [comment]
> When building mdbx myself, I used `Release` build with `/Ob1` switch instead of `/Ob2`.

Yes, this is [known solution](https://github.com/erthink/libmdbx/issues/116#issuecomment-691735471).

**Comment by erthink** [comment]
Seems M$ fixed this issue silently, at least it don't reproduced on the Visual Studio 2019 release 16.10.
