### ISSUE TITLE
Missing linebreak in dist/mdbx.c

### ISSUE THREAD

**Issue by snej** [erthink/libmdbx#156]
(Split off from #155) I noticed that, on macOS 10.15, the amalgamated version of mdbx.c produced by `make dist` has a glitch in line 14:
```c
#define MDBX_ALLOY 1n#define MDBX_BUILD_SOURCERY 9854b516cd42bd97a2447d2f4adfda8cd99464906b15a3646a1409c129fbb1bc_v0_9_2_21_g1c70814
```
The "`n`" before the second `#define` is clearly supposed to be a newline.

This isn't causing any problems that I've noticed. It looks like it'll probably cause the git version field of `mdbx_version` to be empty, but I haven't checked.

This is generated by the following command in the GNUmakefile, at line 323 in my source tree:
```make
dist/@tmp-shared_internals.inc: src/version.c $(ALLOY_DEPS) $(lastword $(MAKEFILE_LIST))
	mkdir -p dist && sed \
		-e 's|#pragma once|#define MDBX_ALLOY 1\n#define MDBX_BUILD_SOURCERY $(MDBX_BUILD_SOURCERY)|' \
...
```
I've tried adding one or more additional backslashes before the `n` but it doesn't have the desired effect.

I'm on commit 3a441d6d3a755e97af803f731fc9059d8818ebd6 from Jan 4.

**Comment by erthink** [comment]
Please check [this](https://github.com/erthink/libmdbx/commit/ed4cb000e413bf12a863e8d6984dabadfc85c5c8).

**Comment by erthink** [comment]
@snej, could you check the fix suggested  above?

**Comment by erthink** [comment]
Fixed for BSD for now, but still fail on MacOS.
Seems MacOS's version of sed have a bug or is really mad/incompatible.
