### ISSUE TITLE
Devel: freelist growth fast

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#158]
- Normally in this workload freelist almost empty (because it’s place where new data coming).
- No DBI drops were performed. 
- Freelist growth to 128Gb
- App did big updates by 500mb batches (semi-random updates/inserts), each such batch did increase freelist size by 7Gb. 
- env: durable | coalesce
- env.SetGeometry(-1, -1, 2Tb, 2Gb, -1, -1)
	

`
Garbage Collection
  Pagesize: 4096
  Tree depth: 1
  Branch pages: 0
  Leaf pages: 1
  Overflow pages: 125845
  Entries: 118
  GC: 128802405 pages
Status of Main DB
  Pagesize: 4096
  Tree depth: 1
  Branch pages: 0
  Leaf pages: 1
  Overflow pages: 0
  Entries: 44

`

**Comment by PaoloRebuffo** [comment]
I did another check on the same DB that @AskAlexSharov  is referring to with:
mdbx_stat -ff

The results are these:
mdbx_stat v0.9.2-146-g2b290e08 (2021-02-01T02:14:28+03:00, T-1a4a5b9dcaec955497b57791b5f86e85331d41d8)
Running for /home/admin/.local/share/turbogeth/tg/chaindata...
Garbage Collection
  Pagesize: 4096
  Tree depth: 1
  Branch pages: 0
  Leaf pages: 1
  Overflow pages: 125845
  Entries: 118
    Transaction 30778, 762 pages, maxspan 8
    Transaction 30779, 314406 pages, maxspan 1264
    Transaction 30780, 355123 pages, maxspan 1370
    Transaction 30781, 396333 pages, maxspan 1659
    Transaction 30782, 433396 pages, maxspan 2146
    Transaction 30783, 464343 pages, maxspan 1143
    Transaction 30784, 500554 pages, maxspan 13691
    Transaction 30785, 518776 pages, maxspan 1717
    Transaction 30786, 567960 pages, maxspan 10625
    Transaction 30787, 616114 pages, maxspan 1944
    Transaction 30788, 609018 pages, maxspan 2756
    Transaction 30789, 669663 pages, maxspan 2257
    Transaction 30790, 711649 pages, maxspan 1647
    Transaction 30791, 743709 pages, maxspan 1141
    Transaction 30792, 784560 pages, maxspan 1871
    Transaction 30793, 786422 pages, maxspan 2519
    Transaction 30794, 839615 pages, maxspan 1332
    Transaction 30795, 861183 pages, maxspan 1521
    Transaction 30796, 903133 pages, maxspan 2225
    Transaction 30797, 922883 pages, maxspan 1755
    Transaction 30798, 934588 pages, maxspan 1539
    Transaction 30799, 953729 pages, maxspan 1118
    Transaction 30800, 952999 pages, maxspan 1086
    Transaction 30801, 874059 pages, maxspan 1277
    Transaction 30802, 927826 pages, maxspan 2065
    Transaction 30803, 941062 pages, maxspan 1702
    Transaction 30804, 943384 pages, maxspan 1679
    Transaction 30805, 953770 pages, maxspan 1381
    Transaction 30806, 1039681 pages, maxspan 1372
    Transaction 30807, 1032001 pages, maxspan 1546
    Transaction 30808, 1022185 pages, maxspan 2720
    Transaction 30809, 1052761 pages, maxspan 2914
    Transaction 30810, 1080020 pages, maxspan 2659
    Transaction 30811, 1094676 pages, maxspan 3582
    Transaction 30812, 1129416 pages, maxspan 1065
    Transaction 30813, 1035649 pages, maxspan 3303
    Transaction 30814, 1109451 pages, maxspan 2897
    Transaction 30815, 1110015 pages, maxspan 1714
    Transaction 30816, 1027829 pages, maxspan 1438
    Transaction 30817, 1066763 pages, maxspan 2404
    Transaction 30818, 1089736 pages, maxspan 1282
    Transaction 30819, 1083146 pages, maxspan 1617
    Transaction 30820, 1109160 pages, maxspan 1656
    Transaction 30821, 1071404 pages, maxspan 2034
    Transaction 30822, 1145504 pages, maxspan 1867
    Transaction 30823, 1093820 pages, maxspan 1097
    Transaction 30824, 1170971 pages, maxspan 3211
    Transaction 30825, 1155608 pages, maxspan 967
    Transaction 30826, 1036616 pages, maxspan 1254
    Transaction 30827, 675415 pages, maxspan 1240
    Transaction 30828, 726937 pages, maxspan 942
    Transaction 30829, 921568 pages, maxspan 1189
    Transaction 30830, 705382 pages, maxspan 1723
    Transaction 30831, 1174585 pages, maxspan 1185
    Transaction 30832, 1177116 pages, maxspan 1524
    Transaction 30833, 1260775 pages, maxspan 2030
    Transaction 30834, 1180386 pages, maxspan 1101
    Transaction 30835, 1037909 pages, maxspan 4038
    Transaction 30836, 1066187 pages, maxspan 2148
    Transaction 30837, 1148342 pages, maxspan 1815
    Transaction 30838, 1128000 pages, maxspan 2733
    Transaction 30839, 1154077 pages, maxspan 2468
    Transaction 30840, 1100664 pages, maxspan 1625
    Transaction 30841, 1214873 pages, maxspan 5253
    Transaction 30842, 1150111 pages, maxspan 1983
    Transaction 30843, 1110115 pages, maxspan 2748
    Transaction 30844, 1035741 pages, maxspan 1670
    Transaction 30845, 1076347 pages, maxspan 2354
    Transaction 30846, 1074318 pages, maxspan 1466
    Transaction 30847, 1236198 pages, maxspan 4572
    Transaction 30848, 1154300 pages, maxspan 981
    Transaction 30849, 1172068 pages, maxspan 1154
    Transaction 30850, 1116697 pages, maxspan 946
    Transaction 30851, 1193521 pages, maxspan 767
    Transaction 30852, 1215108 pages, maxspan 1134
    Transaction 30853, 1261175 pages, maxspan 2131
    Transaction 30854, 1296989 pages, maxspan 1366
    Transaction 30855, 1332523 pages, maxspan 1175
    Transaction 30856, 1296515 pages, maxspan 1106
    Transaction 30857, 1256017 pages, maxspan 1591
    Transaction 30858, 1277296 pages, maxspan 1496
    Transaction 30859, 1299698 pages, maxspan 2898
    Transaction 30860, 1297960 pages, maxspan 5870
    Transaction 30861, 1380515 pages, maxspan 821
    Transaction 30862, 1303303 pages, maxspan 979
    Transaction 30863, 1229278 pages, maxspan 1903
    Transaction 30864, 1276817 pages, maxspan 1215
    Transaction 30865, 1304014 pages, maxspan 1596
    Transaction 30866, 1250338 pages, maxspan 1052
    Transaction 30867, 1341241 pages, maxspan 1427
    Transaction 30868, 1258875 pages, maxspan 2216
    Transaction 30869, 1285635 pages, maxspan 1552
    Transaction 30870, 1324358 pages, maxspan 1729
    Transaction 30871, 1290035 pages, maxspan 1010
    Transaction 30872, 1349746 pages, maxspan 1083
    Transaction 30873, 1373842 pages, maxspan 1131
    Transaction 30874, 1335555 pages, maxspan 890
    Transaction 30875, 1253201 pages, maxspan 1673
    Transaction 30876, 1338068 pages, maxspan 2396
    Transaction 30877, 1246137 pages, maxspan 1493
    Transaction 30878, 1418000 pages, maxspan 1051
    Transaction 30879, 1436294 pages, maxspan 1262
    Transaction 30880, 1461118 pages, maxspan 1726
    Transaction 30881, 1471845 pages, maxspan 2438
    Transaction 30882, 1359062 pages, maxspan 826
    Transaction 30883, 1371490 pages, maxspan 1131
    Transaction 30884, 1331225 pages, maxspan 1719
    Transaction 30885, 1402210 pages, maxspan 2221
    Transaction 30886, 1377805 pages, maxspan 4445
    Transaction 30887, 1407748 pages, maxspan 4137
    Transaction 30888, 1422328 pages, maxspan 4604
    Transaction 30889, 1500705 pages, maxspan 5175
    Transaction 30890, 1425699 pages, maxspan 5668
    Transaction 30891, 1517571 pages, maxspan 3048
    Transaction 30892, 1512082 pages, maxspan 3387
    Transaction 30893, 1532366 pages, maxspan 6354
    Transaction 30894, 1523552 pages, maxspan 6789
    Transaction 30895, 1428003 pages, maxspan 6848
  GC: 128802405 pages
Status of Main DB
  Pagesize: 4096
  Tree depth: 1
  Branch pages: 0
  Leaf pages: 1
  Overflow pages: 0
  Entries: 44

**Comment by erthink** [comment]
1. Please make sure that there are no reading transactions preventing GC/Freelist reclaiming.
This could be done by `mdbx_stat -r` while test running and in best case should show only one (i.e. itself) in the reader table.
For other reader(s), you need to pay attention to the `retained` column, large values in which means that the reader prevents the GC/Freelist from reclaim.
2. Then, seems the [`MDBX_opt_rp_augment_limit`](https://libmdbx.dqdkfa.ru/group__c__settings.html#gga671855605968c3b1f89a72e2d7b71eb3a5b1a57f0af52b62ac57d594f939e06a9) runtime option should be set to large value than default (`262144`) for your use cases. Please thy `mdbx_env_set_option(env, MDBX_opt_rp_augment_limit, 16777216)`.

**Comment by erthink** [comment]
Nonetheless, I will re-check the code.

**Comment by AskAlexSharov** [comment]
1. will do
2. actually we moved our DB towards small values - almost no overflow pages in our db now (or little amount per value). Still increase?

**Comment by AskAlexSharov** [comment]
mdbx_stat -r
```
Reader Table
   #    slot       pid           thread                txnid        lag          used      retained
   1)    [0]    1947447     7f71f63c6740                35329          0    1732043.2M          0.0M
```

**Comment by erthink** [comment]
> actually we moved our DB towards small values - almost no overflow pages in our db now (or little amount per value). Still increase?

The large/overflow pages still need for GC/Freelist itself (i.e. for large list of retired pages).

Presumably, I will have time to deal with this problem tonight, but still carefully watch for long-reading transactions to exclude their impact.

**Comment by AskAlexSharov** [comment]
Increasing MDBX_opt_rp_augment_limit helped for our basic workload. 
Next step - test after big DBI drop.
