### ISSUE TITLE
Building on aarch64

### ISSUE THREAD

**Issue by mahlonsmith** [erthink/libmdbx#159]
Ran into a pile of relocation errors when attempting an ARM build:

```
mdbx++-dylib.o: in function `mdbx::buffer<std::pmr::polymorphic_allocator<char> >::data_preserver::operator int (*)(void*, iovec*, void const*, unsigned long)() const':
/usr/src/debug/mdbx/0.9.3-r0/mdbx.h++:834:(.text._ZNK4mdbx6bufferINSt3pmr21polymorphic_allocatorIcEEE14data_preservercvPFiPvP5iovecPKvmEEv[_ZNK4mdbx6bufferINSt3pmr21polymorphic_allocatorIcEEE14data_preservercvPFiPvP5iovecPKvmEEv]+0x0): dangerous relocation: unsupported relocation
```

Adding `-fPIC` to the `CXXFLAGS` definition of the GNUMakefile allowed it to compile cleanly - I'm not sure if by doing so that causes any other repercussions or unintended consequences - just a heads up.  (I see it's already present for `CFLAGS`)

**Comment by erthink** [comment]
OK, I'll add `-fPIC`.

Although the build for `ARM` and  `aarch64` was tested using `arm-linux-gnueabihf-gcc (Ubuntu 10.2.0-8ubuntu1) 10.2.0` and `aarch64-linux-gnu-gcc (Ubuntu 10.2.0-8ubuntu1) 10.2.0`.
So it could be a gcc and/or binutils issue.

**Comment by erthink** [comment]
I rechecked the situation and came to the conclusion that everything is fine and there is no reason to fix anything:
- the `-fPIC` option is already passed to the C **and** C++ compilers, i.e. **to the both**;
- the build is successful with the ARM and AARCH64 cross-compilers both.
