### ISSUE TITLE
geometry: better assert about invalid value than silently adjust

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#166]
set_geometry has code:
```
 if (bytes2pgno(env, growth_step) > UINT16_MAX)
    growth_step = pgno2bytes(env, UINT16_MAX);
```
It's very unexpected option configured by me was silently changed. 
Also this code is buggy: bytes2pgno can't be used before set env.me_psize is set - but it's not set yet (I passed pagesize=64Kb to set_geometry, but bytes2pgno using 4K value here).

**Comment by AskAlexSharov** [comment]
Also I think - better push people somehow to call set_geometry before calling other methods, because other methods like set_option can use pgno2bytes.

**Comment by erthink** [comment]
I will definitely fix it soon, but literally today/tomorrow I'm digging out another bug inherited from LMDB.
