### ISSUE TITLE
Support building for Windows by MinGW and (maybe) by other compilers.

### ISSUE THREAD

**Issue by erthink** [erthink/libmdbx#17]
Should be taken into account, that at least one additional set of tests **must be implemented and integrated** into `appveyor.yml`:
- validation of cleanup on thread termination (and so on), with respect to glibc bugs #21031 and #21032.
- validation of interoperability with libmdbx.dll and libmdbx.lib, which were built by MSVC 2013/2015/2017.

**Comment by zingchen** [comment]
The current implementation requires Windows 8.1 target or later, whereas current MinGW's library only supports Windows 7 or earlier. Building by MinGW, without a completely new implementation, is therefore impossible.

**Comment by leo-yuriev** [comment]
There are two principal reasons to NOT support Windows earlier 8.1:
1. Windows 8.0 (and all earlier versions) have enough of flaws in the implementation of virtual memory management and corresponding I/O. For instance please read [this thread](http://osronline.com/showthread.cfm?link=250109).
2. I don't able to testing for Windows 8.0 or earlier, just no infrastructure. More over, I don't wanna to spend my time for this.

Historically MDBX was forked for [ReOpenLDAP](https://translate.googleusercontent.com/translate_c?act=url&depth=1&hl=ru&ie=UTF8&rurl=translate.google.com&sl=ru&tl=en&u=https://github.com/ReOpen/ReOpenLDAP/wiki) that running only on Linux. Under this reason I removed support for all OS except Linux. Once again - not able (no time, no resources) to test updated code.

Later, at the beginning of 2017, I added (re-implemented) support Windows (by sponsorship from [Positive Technologies](https://www.ptsecurity.com)), but only for >= 8.1.

**Comment by erthink** [comment]
@zingchen, seems this done now, since:
1. libmdbx is used by Miranda NG, i.e. successfully build and runs on Windows XP and Windows 7. More over the `MDBX_AVOID_CRT` option is provided.
2. building with `CMake` is supported.

Could someone check with MinGW and confirm this?

**Comment by erthink** [comment]
Seems done
