### ISSUE TITLE
mdbx_env_set_geometry with defaults prevents env from being usable

### ISSUE THREAD

**Issue by Thermi** [erthink/libmdbx#170]
Code snippet:
```
 rc = mdbx_env_set_geometry(env,
    0, // size_lower
    -1, // size_now
    INTPTR_MAX, // size_upper
    -1, // growth_step
    -1, // shrink_threshold
    -1); // pagesize
```
Makes `env_open` throw MDBX_TOO_LARGE.

Same for C++ API, because those values from the snippet are the defaults for the geometry class.
What's your advice? The problem doesn't exist with the C API (because there the defaults are different).

**Comment by erthink** [comment]
Related to https://github.com/erthink/libmdbx/issues/166.
