### ISSUE TITLE
Is there a way to increment 1 to a value in db using txn or...

### ISSUE THREAD

**Issue by hiqsociety** [erthink/libmdbx#174]
Is there a way to increment 1 to a value in db using txn or do i have to get the value first, add it inside my golang function then only save it into db?

**Comment by erthink** [comment]
1. In general, libmdbx uses opaque byte sequences to represent keys and/or values.
So historically no universal `increment` operation was provided.
2. See [`mdbx_dbi_sequence()`](https://erthink.github.io/libmdbx/group__c__crud.html#ga27bedd3c425e93440ad82290a5cf2f03).
3. On request, a similar API can be implemented for a value of 4 and 8 bytes in length.
There will be no functional differences from get+set, only slightly less overhead.

**Comment by hiqsociety** [comment]
can you implement one for 1, 4 and 8 bytes? basically 1 byte will do i guess since we can also use the 1byte to simulate 4 and 8...

when do u think this is possible? increment is a huge feature. the overhead will be so much lesser considering how often everyone needs to autoincrement values esp counters etc

**Comment by hiqsociety** [comment]
increment not just 1 but any values e.g. +8 , +13 etc

thx
