### ISSUE TITLE
Possible to fork one version > 128TB?

### ISSUE THREAD

**Issue by hiqsociety** [erthink/libmdbx#176]
Seems like this libmdbx has a good use case for a lot of things.

**Comment by erthink** [comment]
> Seems like this libmdbx has a good use case for a lot of things.

I didn't understand the question.

Nonetheless, **PLEASE** read documentation, at least the three chapters:
1. [Overall](https://erthink.github.io/libmdbx/index.html)
2. [Intoduction](https://erthink.github.io/libmdbx/intro.html)
3. [Getting started](https://erthink.github.io/libmdbx/usage.html#starting)
