### ISSUE TITLE
mdbx.lib built with MSVC LTO prevents linking with lld

### ISSUE THREAD

**Issue by MrSmith33** [erthink/libmdbx#182]
Is it possible to specify an option to `cmake`, so that LTO will be disabled?

I'm building with
```
mkdir build
cd build
cmake -G "Visual Studio 16 2019" -A x64 -D CMAKE_CONFIGURATION_TYPES="Debug;Release;RelWithDebInfo" -D MDBX_AVOID_CRT:BOOL=ON -D MDBX_BUILD_SHARED_LIBRARY:BOOL=OFF ..
cmake --build . --config RelWithDebInfo
```

The workaround I found is to replace in `libmdbx/cmake/compiler.cmake` the `set(MSVC_LTO_AVAILABLE TRUE)` with `set(MSVC_LTO_AVAILABLE FALSE)` to prevent the use of `/LTCG`, which messes with lld linker.

**Comment by erthink** [comment]
Basically LTO should be controllable by the `INTERPROCEDURAL_OPTIMIZATION` (i.e. be the well known CMake's option).

If it will works as you need, then close this issue.
Otherwise clarify/actualize the trouble.

**Comment by MrSmith33** [comment]
Indeed, adding `-D INTERPROCEDURAL_OPTIMIZATION:BOOL=FALSE` worked as needed. Thanks
