### ISSUE TITLE
C++ API Docs ?

### ISSUE THREAD

**Issue by anuragvohraec** [erthink/libmdbx#183]
Hi Team,

Is there any C++ API usage docs.
https://erthink.github.io/libmdbx/group__cxx__api.html

Is there any estimation of when will it be made available ?

**Comment by anuragvohraec** [comment]
A simple example would suffice too.

I tried this to test db file creation:
```c++
#include <iostream>
#include "mdbx/mdbx.h++"
#include <string>

using namespace mdbx;

int main(int, char**) {
    std::cout << "Starting mdbx app!"<< std::endl ;

    env::geometry db_geometry;
    
    env_managed::create_parameters create_param;
    create_param.geometry=db_geometry;


    mdbx::env::operate_parameters operator_param;

    std::string&& db_file_path="./my-db";

    mdbx::env_managed env1 = mdbx::env_managed(db_file_path,create_param, operator_param);


    env1.close();
    
}

 but it gives me error: MDBX_TOO_LARGE

```

**Comment by erthink** [comment]
Seems this is a bug.

**Comment by erthink** [comment]
Briefly:
- By default, the upper limit of a database is set to the maximum possible value supported by MDBX (≈128.0 TiB for 64-bit platforms), which is too large for most of machines.
- Therefore, this leads to an error, but which exactly one depends on the OS and the MDBX version (`MDBX_TOO_LARGE` for last releast, `MDBX_ENOMEM` for current master, `ERROR_OUTOFMEMORY`/`ERROR_NOT_ENOUGH_MEMORY`/`ERROR_INSUFFICIENT_RESOURCE_FOR_SPECIFIED_SHARED_SECTION_SIZE`/`ERROR_DISK_FULL`/`ERROR_FILE_TOO_LARGE`, etc on Windows);
- I need to think about how to fix this rationally and reasonable.

**Comment by erthink** [comment]
a@anuragvohraec, thanks for reporting this flaw.
The problem went unnoticed, because in the current usage scenarios and tests, the by-default values of some parameters are not used.
