### ISSUE TITLE
Is it bad idea to rename DBI?

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#189]

**Comment by erthink** [comment]
Rrenaming is not (historically) implemented, since these names are not visible to the end user and therefore renaming was never necessary yet.

On the other hand, it is not difficult to support it, if a reasonable use case will be shown.

**Comment by AskAlexSharov** [comment]
No real use-case, just our DBI names were created (historically) "somehow", and some of them was prefixes in LevelDB. 
Now we have DBI names like: "b", "B", "PLAIN-CST2", "clique-" 
But with lmdb/mdbx no reason to save characters on DBI names. 
It just would be nice to rename them to something meaningful without big db migrations.

**Comment by AskAlexSharov** [comment]
But it's not really important because we anyway plaining "non-backwards compatible release" to switch from LMDB to MDBX. And we can rename DBI's on APP side during that "non-backwards compatible release"
