### ISSUE TITLE
Consider to delete MDBX_BUILD_TIMESTAMP

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#201]
There is no logic based on this constant. 

But it breaks reproducibility of app builds: `shasum -a256 mybinary` is different from build to build only because of MDBX_BUILD_TIMESTAMP. 
Reproducibility checksum useful for security reasons - to check that no malware code was embedded into app sources during "release binary artifacts" process.

**Comment by erthink** [comment]
It was assumed that the ability to predefine `MDBX_BUILD_TIMESTAMP` for builds reproducibility would be added.
Looks like it's time to do it.

**Comment by AskAlexSharov** [comment]
It works:
```
MDBX_BUILD_TIMESTAMP=unknown make config.h
make mdbx-static.o
```
