### ISSUE TITLE
Question: how to get original flags a map was created with ?

### ISSUE THREAD

**Issue by AndreaLanfranchi** [erthink/libmdbx#211]
Though I think the question is pretty explicative here a scenario.
Say I want to create a clone of a map (or bucket or table ... the naming is fancy) and I need to derive original `key_mode` and `value_mode` so I can properly insert data in target.
How can I do that ?

**Comment by AndreaLanfranchi** [comment]
Suggestion ... can we get map flags being reported as result of `txn.get_map_stat(...)` ?

**Comment by erthink** [comment]
Basically: open dbi with `MDBX_DB_ACCEDE` flag and get star, but for now "accede" not available in the `C++` API.

**Comment by AndreaLanfranchi** [comment]
But from my understanding MDBX_Accede inherits the flags of the already opened ENV. It has nothing to do with map flags. Also I want to create a clone of the table in the same DB (so accede is not relevant IMHO)

**Comment by AndreaLanfranchi** [comment]
And get stat from map does not return creation flags (checked in core.c)

**Comment by erthink** [comment]
I'm on my way now and can't answer in detail.
Briefly: 
- it looks like you are confusing the flags/options of the environment and the db (key-value map).
- the env flags are not persistent;
- about db flags I noticed above.

**Comment by AndreaLanfranchi** [comment]
Sorry for delayed response  
Yes sorry I have confused `MDBX_ACCEDE` (which is `env` related) with `MDBX_DB_ACCEDE` (which is dbi related). To be honest the confusion is also due to the fact `MDBX_DB_ACCEDE = MDBX_ACCEDE` whilest being in two different enums.

Thank you.

**Comment by AndreaLanfranchi** [comment]
Just for reference it is possible to do this using C++ API

```
        auto named_map{txn.open_map("whatever")};
        auto info{txn.get_handle_info(named_map)};
```

Info struct contains both flags and two helper methods to get `valuemode` and `keymode`
