### ISSUE TITLE
Will multithreaded writing block and wait automatically

### ISSUE THREAD

**Issue by 007gzs** [erthink/libmdbx#216]
Will multithreaded writing block and wait automatically？
I tested using multithreading to write a database file.
got error EAGAIN(11) in mdbx_env_open or mdbx_txn_begin.
I want to let multithreading write when blocking wait need how to configure.

my test code 
```
#include <stdio.h>
#include <pthread.h>
#include "mdbx.h"
#define THREAD_NUM 100
void *do_test(void *arg)
{
    MDBX_env* env = NULL;
    MDBX_txn* txn = NULL;
    int err;
    printf("%p start\n", arg);
    err = mdbx_env_create(&env);
    if (err != MDBX_SUCCESS)
    {
        printf("mdbx_env_create %d\n", err);
        goto fail;
    }

    mdbx_env_set_geometry(env, 1024 * 1024, -1, 1024 * 1024 * 1024, 1024 * 1024, -1, -1);
    err = mdbx_env_open(env, "test", 0, 0664);
    if (err != MDBX_SUCCESS)
    {
        printf("mdbx_env_open %d\n", err);
        goto fail;
    }
    err = mdbx_txn_begin(env, NULL, 0, &txn);
    if (err != MDBX_SUCCESS)
    {
        printf("mdbx_txn_begin %d\n", err);
        goto fail;
    }
    mdbx_txn_commit(txn);

fail:
    if (txn) mdbx_txn_abort(txn);
    if (env) mdbx_env_close(env);
    return NULL;
}
int main()
{
    pthread_t pthread[THREAD_NUM];
    for (int i = 0; i < THREAD_NUM; i++)
    {
        pthread_create(pthread + i, NULL,do_test, pthread+i);
    }
    for (int i = 0; i < THREAD_NUM; i++)
    {
        pthread_join(pthread[i], NULL);
    }
    return 0;
}
```

**Comment by erthink** [comment]
> Will multithreaded writing block and wait automatically？

Yes, of cause.

> I tested using multithreading to write a database file.
> got error EAGAIN(11) in mdbx_env_open or mdbx_txn_begin.

You should not open the same database multiple times from a single process.
Especially trying to do this by the concurrent threads.

> I want to let multithreading write when blocking wait need how to configure.

Please RTFM: https://libmdbx.dqdkfa.ru/usage.html#starting
