### ISSUE TITLE
Signature upgrade failed 

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#242]
mdbx_setup_dxb:15310 updating db-format signature for meta[1], txnid 568904, error -30779

It happens for rare users and I can’t reproduce it. What info I can provide here?

**Comment by erthink** [comment]
Apparently the `MDBX_PROBLEM` (-30779) is raised [here](https://github.com/erthink/libmdbx/blob/773172cc99edb4f3c19c09b3863ac9f0737aff45/src/core.c#L12281-L12283) where `mdbx_override_meta()` called from [here](https://github.com/erthink/libmdbx/blob/773172cc99edb4f3c19c09b3863ac9f0737aff45/src/core.c#L11948).
There seems to be some bug somewhere.

Immediately before the error message you specified, there should be another one clarifying the specific problem in the meta page.
Could you provide it?

**Comment by AskAlexSharov** [comment]
mdbx_validate_meta:13651 meta[1] used-bytes (1740878180352) beyond filesize (1740877877248), skip it
mdbx_validate_meta:13651 meta[1] used-bytes (1740878180352) beyond filesize (1740877877248), skip it
mdbx_validate_meta:13651 meta[1] used-bytes (1740878180352) beyond filesize (1740877877248), skip it
mdbx_setup_dxb:15310 updating db-format signature for meta[1], txnid 568904, error -30779

**Comment by erthink** [comment]
Got it and is coincided with my guess.
This is a minor bug that I will fix before the end of the day.
Thank you for reporting.
