### ISSUE TITLE
MDBX_GET_BOTH not returning MDBX_NOTFOUND for missing value

### ISSUE THREAD

**Issue by kriszyp** [erthink/libmdbx#243]
Using mdbx_cursor_get with MDBX_GET_BOTH on a MDBX_DUPSORT database, where the provided key exists and has values, but the provided value does not exist for the key, will return `0`.
Expected behavior: MDBX_GET_BOTH should position the cursor at exactly the key and value provided, and if the exact key/value dooes not exist, it should return MDBX_NOTFOUND (this is the behavior in LMDB with MDB_GET_BOTH, which does return MDB_NOTFOUND if the key/value does not exist).

**Comment by erthink** [comment]
I will check this.
As a temporary solution, I suggest you try [MDBX_SET_LOWERBOUND](https://erthink.github.io/libmdbx/group__c__cursors.html#gga501baff3bcff7e8e7818b4d412a2a6d5a00baa9068c2fdb8b159ef11979636ab4), maybe it will be more convenient.

**Comment by kriszyp** [comment]
That works great, thank you!

**Comment by erthink** [comment]
@kriszyp, thank you for reporting.

**Comment by kriszyp** [comment]
No problem, thanks for the quick response. The JS library, lmdbx-js (formerly called lmdbx-store) is really stabilizing and working well with libmdbx, I think, and I am hoping to add support for Deno soon.
