### ISSUE TITLE
add MDBX_KEYFIXED like MDBX_INTEGERKEY / MDBX_DUPFIXED

### ISSUE THREAD

**Issue by gcxfd** [erthink/libmdbx#244]
I want use mdbx store ( public-key - ipv4-addr-port )  and (ipv4-addr-port - public-key), 
the key is always 32 bytes , the ipv4-addr-port is always 6 bytes
maybe add support something like `MDBX_KEYFIXED` just as MDBX_INTEGERKEY / MDBX_DUPFIXED  will save space

**Comment by erthink** [comment]
Such feature (i.e. the fixed key size) couldn't be implemented for libmdbx, since required change the database format which is frozen few years ago.

On the other hand, this is not a problem because the fixed key size feature only reduces overhead, but does not interfere with any use cases.

**Comment by gcxfd** [comment]
thanks for reply

maybe can support this when MithrilDB release  ^_^
