### ISSUE TITLE
Build failure without kernel/libc-devel headers

### ISSUE THREAD

**Issue by kriszyp** [erthink/libmdbx#245]
I received an error `libmdbx/mdbx.c:639:10: fatal error: linux/sysctl.h: No such file or directory` when trying to build libmdbx on alpine (docker image node:12.22-alpine):
https://github.com/kriszyp/lmdbx-js/runs/4281817650?check_suite_focus=true#step:6:11
Is lidbmdbx supported on alpine, or do you know if I am missing anything obvious in trying to build on alpine?

**Comment by erthink** [comment]
The `linux/sysctl.h` is a system/kernel-related header which is available within `linux-headers` and/or `linux-libc-dev` packages.

Nonetheless, this header actually not needed for now, i.e. it is an excessively include.
It seems I just forgot to remove its inclusion. I'll fix it now.
