### ISSUE TITLE
Assertion `head_txnid != head_txnid' failed when using MDBX_SAFE_NOSYNC

### ISSUE THREAD

**Issue by kriszyp** [erthink/libmdbx#257]
On my linux box, after loading a bunch of entries into a new database with `MDBX_SAFE_NOSYNC` enabled, if I restart the process, libmdbx frequently crashes when opening with:
```
mdbx:15149: mdbx_setup_dxb: Assertion `head_txnid != head_txnid' failed
```
Do you know if that indicates something in particular that I am doing wrong?

**Comment by erthink** [comment]
This nasty typo was fixed back in October.
Pleas use the last release or the current `master` branch.
