### ISSUE TITLE
fails to compile under termux (android) (v0.11.3)

### ISSUE THREAD

**Issue by basiliscos** [erthink/libmdbx#258]
[termux](https://termux.com/) is an terminal with linux headers + apt package manager.
 
 My project is successfully configured (cmake), but fails to compile. I think, it should either do not configure or build. 

The error is on the screenshot: 

![photo_2022-01-05_13-41-49](https://user-images.githubusercontent.com/3630048/148204812-5f841656-a328-402f-a2d9-d190aa7a2746.jpg)

**Comment by erthink** [comment]
Assuming I can fix this quickly - firstly run `make` with the `--keep-going` option to get all such problems and fix ones at once.

**Comment by erthink** [comment]
Seems the CI for Android should be added.
