### ISSUE TITLE
mdbx_env_open returns error 22 (Invalid argument) on 32-bit Android devices

### ISSUE THREAD

**Issue by leisim** [erthink/libmdbx#262]
I tried to open an environment (with and) without any options or flags (mode `0600`) all 64-bit targets work without issues but on older 32-bit Android devices I get error 22 when opening an environment.

**Comment by erthink** [comment]
Presumably the problem is that 32-bit android kernels do not allow you to create large-size memory mappings.
Please try create/open a small sized DB, about of 1 Mb.

**Comment by leisim** [comment]
I tried not setting the geometry. Isn't the default size pretty small?

**Comment by erthink** [comment]
> I tried not setting the geometry. Isn't the default size pretty small?

Should be.

Could you run your exe/application, or a minimal testcase, under the `strace` ?

**Comment by leisim** [comment]
Unfortunately that doesn't work on Android. The debugging options for native code are very limited (non-existent?).

I hoped you might have an idea what could be wrong but I understand that it's difficult without more information.

**Comment by erthink** [comment]
> I hoped you might have an idea what could be wrong but I understand that it's difficult without more information.

No ideas, except the mapping size may made behavior significantly difference under a 32- and 64-bit environments.

**Comment by erthink** [comment]
Please try [this](https://source.android.com/devices/tech/debug/strace).
There is no other reasonable way.

**Comment by leisim** [comment]
Oh that's cool. But it requires a rooted 32-bit device. Will take me some time to get it. I'll post my findings here :+1:

**Comment by erthink** [comment]
Please write down what you got.
Otherwise, there is a risk that I will significantly postpone fixing this issue, even if it will be confirmed.

**Comment by leisim** [comment]
Sorry, I still don't have a 32-bit Android device. It's no problem if the fix takes a little longer 🙂

**Comment by erthink** [comment]
> Sorry, I still don't have a 32-bit Android device. It's no problem if the fix takes a little longer slightly_smiling_face

Assume the [AVD](https://developer.android.google.cn/studio/run/emulator.html) will enough, but not sure.
