### ISSUE TITLE
EXC_BAD_ACCESS on older iOS devices for first launch

### ISSUE THREAD

**Issue by simc** [erthink/libmdbx#267]
Hey,

I get the following error for older iPhones like the iPhone SE. It only happens when the app is launched for the first time. Any idea how to fix it?
<img width="1492" alt="Screenshot 2022-02-13 at 12 19 11" src="https://user-images.githubusercontent.com/13610195/153750660-522acae4-6a7c-4f60-b69d-c0c574ba0d13.png">

**Comment by erthink** [comment]
I think it's some kind of defect in older versions of iOS or incompatibility with standards like POSIX.
Please set breakpoing above to the `rc = alloc_page_buf();` and step into the `mdbx_memalign_alloc()`.
This will allow you to understand exactly which function is called on the problematic OS and search for information about this trouble and methods to work around it.

**Comment by leisim** [comment]
Thanks! I will try that. But the device runs the latest iOS 15 🤔

**Comment by leisim** [comment]
This is what I get. `me_pbuf` already has a value.
<img width="1492" alt="Screenshot 2022-02-13 at 15 00 38" src="https://user-images.githubusercontent.com/13610195/153756637-62255fa2-594e-472d-ba2a-092685a731a3.png">

**Comment by erthink** [comment]
I found potential bug that could trigger such access violation in some cases.
Please check out the current `devel` branch.

If the problem persists, then set the breakpoint inside the `mdbx_memalign_alloc()`. So you will catch the buffer allocation.

**Comment by leisim** [comment]
`me_pbuf` is still not `0` so `mdbx_memalign_alloc` is not called. 

Could this code be problematic?
https://github.com/isar/isar-core/blob/8c3c2dd83f125501ac859e0b01ca39ae80f2f692/src/mdbx/env.rs#L35-L50

It is needed because iOS only grants a limited amount of virtual memory.

**Comment by leisim** [comment]
Oh, it is actually called but in the previous iteration of my loop.
<img width="1492" alt="Screenshot 2022-02-13 at 17 12 24" src="https://user-images.githubusercontent.com/13610195/153762060-9077f0a8-0bdf-4183-b41e-12c174425b3f.png">

**Comment by erthink** [comment]
> Could this code be problematic? https://github.com/isar/isar-core/blob/8c3c2dd83f125501ac859e0b01ca39ae80f2f692/src/mdbx/env.rs#L35-L50

Yes.
This is a really strange solution, and the such case was overlooked.
However, I should fix this, i.e. make libmdbx code more idempotence.

**Comment by erthink** [comment]
@leisim, Please check this and close issue on success.
Thank you for reporting.

**Comment by leisim** [comment]
@erthink It works! Thanks a lot. I know it is a bit unusual but [mai.ru also uses this method in their app](https://discourse.world/h/2020/06/05/Shine-and-poverty-key-value-database-LMDB-in-applications-for-iOS). I didn't find a better solution.
