### ISSUE TITLE
mdbx_meta_head is not defined

### ISSUE THREAD

**Issue by yperbasis** [erthink/libmdbx#273]
In the latest release (v0.11.5) `mdbx_meta_head` is [used](https://github.com/erthink/libmdbx/blob/v0.11.5/src/core.c#L7380) in `mdbx_txn_valgrind` , but is not defined anywhere.

**Comment by erthink** [comment]
Thank for reporting.
Will be fixed promptly.

**Comment by erthink** [comment]
Be noted for #269 (still digging it).

**Comment by erthink** [comment]
To the topic of using Valgrind see https://github.com/erthink/libmdbx/issues/82.
