### ISSUE TITLE
Reference mdbx4s in the bindings table

### ISSUE THREAD

**Issue by david-bouyssie** [erthink/libmdbx#274]
Hi @erthink 

I have just pushed on Github a new libmdbx binding targetting the Scala platform: https://github.com/david-bouyssie/mdbx4s

It is building on the JVM (by wrapping Castotech MDBXJNI) and on Scala Native (using direct binding to the libmdbx library).

It's not yet on Maven Central bu the Github Workflow CI is green :)

**Comment by erthink** [comment]
Waiting until tests be done without any issues.

**Comment by david-bouyssie** [comment]
Done :)
