### ISSUE TITLE
Documentation about shared library build only

### ISSUE THREAD

**Issue by david-bouyssie** [erthink/libmdbx#275]
Currently I'm using the `make all` to generate the libmdbx shared library.
I was wondering what would be the `make` configuration:
1. to build only the shared library without the other programs
2. containing the "most appropriate" LIBMDBX build settings (it seems that there are many options available)

Thanks for this great project.

**Comment by erthink** [comment]
> 1. to build only the shared library without the other programs

Ok, I'ill add `lib-static` and `lib-shared` targets.
However the `make lib` and `make help` are available now.

> 2. containing the "most appropriate" LIBMDBX build settings (it seems that there are many options available)

This is just by default.
Nonetheless, build by `CMake` is recommended for complex and/or non-default cases.

**Comment by david-bouyssie** [comment]
Ok thanks, then I'll switch to `make lib`  for now.
