### ISSUE TITLE
Tracking DB size increase

### ISSUE THREAD

**Issue by castortech** [erthink/libmdbx#277]
We have a simple mechanism that looks for how full the db is via stats and runs every minute to start reporting when the db is over 80% full and then will take other steps (reporting, no write, etc) if it reaches 95%.

A few days ago we reached that threshold when the db got too full (even got MDBX_MAP_FULL: Environment mapsize limit reached,rc:MAP_FULL), after system starting the day at 46% and adding a fair amount of data, but nothing to account for the increase

What seems to have happened is that the db trees restructure themselves (my assumption) and that ended up with a massive growth not directly related to the data size.

Here are the start stats:
`
Info:EnvInfo [geo={lower=1073741824, upper=8589934592, current=4294967296, shrink=2147483648, grow=1073741824},
mapSize=8589934592, lastPgNo=982177, lastTxnId=14854, latterReaderTxnId=14854, SelfLatterReaderTxnId=14854,
meta0TxnId=14854, meta0Sign=-1, meta1TxnId=14852, meta1Sign=-1, meta2TxnId=14853, meta2Sign=-1, maxReaders=630, numReaders=0, dxbPageSize=4096, sysPageSize=4096,
bootId={current={x=140555831817288, y=140556492475936}, meta0={x=140556492475936, y=140557980919808}, meta1={x=140556492475936, y=140557980922240}, meta2={x=140556492476232, y=140557980919808}},
unsyncVolume=140556492475984, autosyncThreshold=140564096364424, sinceSyncSeconds16dot16=3687714400, autosyncPeriodSeconds16dot16=32725, sinceReaderCheckSeconds16dot16=2704859265, mode=32727,
pgopStat={newly=140556492476312, cow=140556492476184, clone=140555831221600, split=140557980919808, merge=140563609957520, spill=140555831221600, unspill=0, wops=140555831221584}]
% Full:46.833847%
`

Then we ended up with:
`
Info:EnvInfo [geo={lower=1073741824, upper=8589934592, current=8589934592, shrink=2147483648, grow=1073741824}, mapSize=8589934592, lastPgNo=2097151, lastTxnId=15185, latterReaderTxnId=15185, SelfLatterReaderTxnId=15185, meta0TxnId=15184, meta0Sign=-1, meta1TxnId=15185, meta1Sign=-1, meta2TxnId=15183, meta2Sign=-1, maxReaders=630, numReaders=16, dxbPageSize=4096, sysPageSize=4096, bootId={current={x=140121657882336, y=140138511497345}, meta0={x=140130774534144, y=140130774534144}, meta1={x=140130250247264, y=140121657882456}, meta2={x=140130774534976, y=140121657882768}}, unsyncVolume=140121657882496, autosyncThreshold=140130774534144, sinceSyncSeconds16dot16=2644817664, autosyncPeriodSeconds16dot16=32624, sinceReaderCheckSeconds16dot16=2644967930, mode=32626, pgopStat={newly=8763527424, cow=65911128, clone=163208761344, split=25742, merge=697944, spill=100711, unspill=40963340, wops=15185}]
% Full:99.999954%
`

We can see that the lastPgNo went from 982177 to 2097151 and the db was already at its maximum upper size.

Is there any way, looking at the stats, to determine how close we are to a restructuring and anticipate such event and being able to take proactive action.

Thanks
Alain

**Comment by erthink** [comment]
Fistly, it looks like there is bug(s) in your code because the output shown contains many inadequate values, for example, as if address are used instead of values (starting from `=140....`).

Next, please use & show the output of `mdbx_chk -vvv`, also the `mdbx_chk -vvvv` and `mdbx_chk -vvvvv` could be useful for analysis. This will show more relevant information, including number of branch and leaf pages, etc.

Last, please read sections ["Long-lived read transactions"](https://erthink.github.io/libmdbx/intro.html#long-lived-read) (including [hsr-callback](https://erthink.github.io/libmdbx/group__c__err.html#gaedc09dd7e0634163be8aafdf00d7db77)) and ["Large data items and huge transactions"](https://erthink.github.io/libmdbx/intro.html#autotoc_md18) - there are only two these reasons for the DB growth. Oh, and also the details of [`MDBX_SAFE_NOSYNC`](https://erthink.github.io/libmdbx/group__c__opening.html#gga9138119a904355d245777c4119534061a586d75ff2fd68aed647a60ea7984ed85) mode if you are used it.

**Comment by castortech** [comment]
Thanks for the info and pointing the bug, will fix those. 

I will check for long lived transactions but I think I should be OK there. 

Our transactions are mostly all small in terms of records and size (almost no record over 4-8k and most < 1k). But here there was one large transaction creating over 20k "records" which will be 4-5 times more entries in mdbx and one such record has a long 1MB field in this case.  So this might have been the cause of the issue.

**Comment by castortech** [comment]
Leonid,

Sorry as this might be a stupid question, but looking at address vs values that you identified. All of those are uint64_t that could be a pointer or just a value. If they are indeed pointers, do they have significant values that can be de-referenced ?

**Comment by erthink** [comment]
I didn't fully understand your question.
But anyway, the bug(s) existence is obviously.
So you need to check the code of your bindings, at least enable checking of the arguments types in the compiler and resolve all warnings.
