### ISSUE TITLE
Apple's Clang 12+ and deprecation treated as error

### ISSUE THREAD

**Issue by AndreaLanfranchi** [erthink/libmdbx#278]
While trying to build Silkworm using Clang 12+ toolset we get this error :

```
In file included from /Users/enriavil1/Desktop/project/silkworm/node/silkworm/db/mdbx.hpp:29:
/Users/enriavil1/Desktop/project/silkworm/third_party/libmdbx/mdbx.h++:3017:5: error: definition of implicit copy assignment operator for 'operate_options' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
    operate_options(const operate_options &) noexcept = default;
    ^
/Users/enriavil1/Desktop/project/silkworm/node/silkworm/db/mdbx.cpp:121:16: note: in implicit copy assignment operator for 'mdbx::env::operate_options' first required here
    op.options = op.options_from_flags(static_cast<MDBX_env_flags_t>(flags));
               ^`
```

Apparently Clang 12+ complains about the lack of user-defined copy assignment operator when a user defined (though defaulted) copy contructor is present. No problems on GCC and MSVC

**Comment by erthink** [comment]
I checked the build using Clang-12 on Linux (i.e. not an Apple branch):
```
$ CC=clang-12 CXX=clang++-12 make
// TIP: Use `make V=1` for verbose.
// TIP: Clone and build the https://github.com/pmwkaa/ioarena.git within a neighbouring directory for availability of benchmarking.
  MDBX_BUILD_OPTIONS   = -DNDEBUG=1
  MDBX_BUILD_TIMESTAMP = 2022-03-18T14:11:06+0300
// TIP: Use `make options` to listing available build options.
  CC       =/usr/bin/clang-12 | Ubuntu clang version 12.0.1-8build1
  CFLAGS   =-std=gnu11 -O2 -g -Wall -Werror -Wextra -Wpedantic -ffunction-sections -fPIC -fvisibility=hidden -pthread -Wno-error=attributes -fno-semantic-interposition -Wno-unused-command-line-argument -Wno-tautological-compare
  CXXFLAGS =-std=gnu++2b -O2 -g -Wall -Werror -Wextra -Wpedantic -ffunction-sections -fPIC -fvisibility=hidden -pthread -Wno-error=attributes -fno-semantic-interposition -Wno-unused-command-line-argument -Wno-tautological-compare
  LDFLAGS  =-Wl,--gc-sections,-z,relro,-O1 -lm -lrt -pthread
// TIP: Use `make help` to listing available targets.
  CLEAN for build with specified flags... Ok
  MAKE src/version.c
  MAKE src/config.h
  CC mdbx-static.o
  CC mdbx++-static.o
  AR libmdbx.a
  CC mdbx-dylib.o
  CC mdbx++-dylib.o
  LD libmdbx.so
  CC+LD mdbx_stat
  CC+LD mdbx_copy
  CC+LD mdbx_dump
  CC+LD mdbx_load
  CC+LD mdbx_chk
  CC+LD mdbx_drop
$ _
```

So there no any warnings using `-std=gnu++2b -Wall -Werror -Wextra -Wpedantic -Wno-error=attributes -fno-semantic-interposition -Wno-unused-command-line-argument -Wno-tautological-compare` from `clang 12.0.1-8build1`.

In addition, I previously checked the build using all more or less current versions of gcc(4.8, 5.0, ..., 9, 10, 11) and clang (3.9, 4.0, ... 11, 12, 13, 14, 15-devel), in the C++ standards mode 11/14/17/20/23. No any warnings at all, using `make` (with flags generated/choised inside `GNUmakefile` like noted above) flags and `CMake` (with flags by `CMakeLists.txt`).

**Comment by AndreaLanfranchi** [comment]
So maybe we're doing somehing wrong [here](https://github.com/erthink/libmdbx/issues/278) ?
The issue arises at line 121 where we copy assign operating options

**Comment by AndreaLanfranchi** [comment]
For the sake of completeness our CMake settings include
```
# Compiler enforcements on Silkworm
if(NOT MSVC)
  add_compile_options(-Werror -Wall -Wextra)
  add_compile_options(-Wshadow -Wimplicit-fallthrough -Wsign-conversion)
  add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-Wold-style-cast>)
  add_compile_options(-Wno-missing-field-initializers)
  if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    add_compile_options(-Wno-attributes)
  endif()
  if(CMAKE_CXX_COMPILER_ID MATCHES "Clang" AND CMAKE_SYSTEM_NAME MATCHES "Darwin")
    add_compile_definitions(_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS)
    add_compile_options(-Wthread-safety)
  endif()
endif()

```

**Comment by erthink** [comment]
Just now I added `-Wdeprecated-copy` explicitly - no warnings.
Please show `clang --version`.

**Comment by AndreaLanfranchi** [comment]
Is Clang 13.1.6

**Comment by erthink** [comment]
Also please try `make` and `CMake` using libmdbx' build scripts/files.

**Comment by erthink** [comment]
re-checked now with explicitly `-Wdeprecated-copy` by clang versions:
 - 15.0.0-++20220317114158+9c632b61ebf2-1~exp1~20220317114252.356 (last night build)
 - 14.0.0-++20220217064845+4dc3cb8e3255-1~exp1~20220217184944.62 (last night build)
 - Ubuntu 13.0.0-2
 - Ubuntu 12.0.1-8build1
 - Ubuntu 11.0.1-2ubuntu5
 
Thus I assume the reason is an one of Apple's branch flaws.

On the other hand, such default-ctor and default-copy-ctor are not required, but needed only to avoid warnings/errors from other and/or older compilers.
So I would like to hear the opinion of C++ experts on how best to proceed.

**Comment by enriavil1** [comment]
> Tried running it with `-Wdeprecated-copy` explicitly as well, but it still gives the same error. 

`/Users/enriavil1/Desktop/project/silkrpc/silkworm/third_party/libmdbx/mdbx.h++:3017:5: error: definition of implicit copy assignment operator for 'operate_options' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
    operate_options(const operate_options &) noexcept = default;
    ^
/Users/enriavil1/Desktop/project/silkrpc/silkworm/node/silkworm/db/mdbx.cpp:121:16: note: in implicit copy assignment operator for 'mdbx::env::operate_options' first required here
    op.options = op.options_from_flags(static_cast<MDBX_env_flags_t>(flags));`

**Comment by erthink** [comment]
> Tried running it with `-Wdeprecated-copy` explicitly as well

I used `-Wdeprecated-copy` to explicitly enabled affected warning, to be sure it is enabled regardless compiler defaults and/or dependings from other options.
But you don't need this option.

**Comment by enriavil1** [comment]
> > Tried running it with `-Wdeprecated-copy` explicitly as well
> 
> I used `-Wdeprecated-copy` to explicitly enabled affected warning, to be sure it is enabled regardless compiler defaults and/or dependings from other options. But you don't need this option.

I tried it just to make sure, but I believe that it might also be related to the apple compiler.

**Comment by enriavil1** [comment]
It seems the problem is the latest version of apple's command line tools package. I was running version 13.3, but after downgrading to 13.2 I receive no issues.
