### ISSUE TITLE
AIX environment is needed for testing (i.e. ssh access)

### ISSUE THREAD

**Issue by erthink** [erthink/libmdbx#68]

**Comment by leo-yuriev** [comment]
The [polarhome.com](http://www.polarhome.com/) service(s) couldn't be used because `ERROR: E-mail address seems not to be valid`.

And support@polarhome.com not respond since 2019-11-30 (msg-id `<CAO2+NUCa4fu-bJLyinJZBw9UT6D_ts6ZKw_nqfEFPrFMegHqUw@mail.gmail.com>`).

**Comment by erthink** [comment]
Obsolete.
