### ISSUE TITLE
Website link is broken (http://leo-yuriev.github.io/libmdbx/)

### ISSUE THREAD

**Issue by snej** [erthink/libmdbx#84]
The Github project's associated web page is http://leo-yuriev.github.io/libmdbx/ ... this used to work a month ago but returns a 404 now. Might want to update it.

**Comment by erthink** [comment]
Thanks for the report.

**Comment by erthink** [comment]
Corrected where I noticed, but I will look for broken links in other places.

**Comment by erthink** [comment]
Seems done.
