### ISSUE TITLE
About the Rust bindings

### ISSUE THREAD

**Issue by Kerollmops** [erthink/libmdbx#85]
Hey @erthink,

I have made great progress on the mdbx Rust bindings today, it seems like every mdbx functions are detected, are correctly built, and the documentation is displayed for items that are documented with the doxygen syntax. 🎉

You can check that by [first installing Rust](https://www.rust-lang.org/learn/get-started), cloning the repo, and executing the following commands:
```bash
git clone https://github.com/Kerollmops/mdbx-rs.git
cd mdbx-rs/
cargo doc --open
```

However there is a little something that I would like to improve, most of the generated functions signatures do not see their comments displayed in the documentation, it is obviously because the comments are not in a valid doxygen format.

I would also like to fix the version use by the Rust binding, I would like the Rust binding major version number to follow the mdbx major one. And the git submodule to be a fixed tag too. I will do that in a future version that I will publish to the official Rust package repo.

Is there a way to ask make (or clang), to avoid creating all of the dSYM debug symblos? In Rust we have two ways of compiling a crate, with of without the debug symbols, I would like to be able to control that behavior.

PS: Would it be also possible to change the name displayed on the README? I would perfer you use Kerollmops instead of Clément Renault 😄 Thanks!

**Comment by Kerollmops** [comment]
I looked more closely to the comment and documentation generation issue related to [bindgen](https://github.com/rust-lang/rust-bindgen), and I found out that the documentation is produced only on comments starting with `/**` and not `/*`.

I will investigate.

**Comment by erthink** [comment]
@Kerollmops, it is not everything is clear with the code comments for autogeneration of documentation:
   - On the one hand, it it seems to be useful to use Doxygen/Javadoc format to automatically docs generation.
    - On the other hand, this clogs the header file and makes it difficult to read comments with the API description.

I am of the opinion that Doxygen/Javadoc is useful for projects with a complex hierarchy of subdirectories and a large number of header files, i.e. when the API description is spread across several files and it is difficult to find anything.

In contrast, libmdbx has only single public header file that contains both the introductory documentation and the API description along with the declaration of structures and functions. Therefore, using Doxygen/Javadoc doesn't seem so necessary.

I asked several developers I know about what they would choose. Most would like to see both a clean h file and separate documentation with hyperlinks. So I haven't changed anything yet, but it's possible that the original decision should be reconsidered.

**Comment by Kerollmops** [comment]
Hey @erthink,

I have made some progress on [the mdbx-sys bindings](https://github.com/Kerollmops/mdbx-rs) today and [made heed work correctly with it](https://github.com/Kerollmops/heed/compare/move-to-mdbx) (at least the test I made) 🎉

But I have a big problem with the way mdbx compiles, currently the version of mdbx is based on the git branches and tags. Unfortunately cargo forces the repository to not depend on this kind of VCS tools, because of that I have made ugly workarounds to make that work.

I would like to know if there would be a better way of pre-computing the [src/elements/version.c file](https://github.com/erthink/libmdbx/blob/8f5ae79b51b5785f745183afbf5a2cae856940f0/GNUmakefile#L186) and packing this in something like a tarball, it is probably what you meant by "amalgamated source code"?

**Comment by erthink** [comment]
Hi @Kerollmops,

> I would like to know if there would be a better way of pre-computing the src/elements/version.c file and packing this in something like a tarball, it is probably what you meant by "amalgamated source code"?

The "amalgamated source code" is exactly for this, and covered by `dist` target in the `GNUmakefile`, i.e. `make dist` produced "amalgamated source", including tarball. I guess [`Build Scripts`](https://doc.rust-lang.org/cargo/reference/build-scripts.html) should be enough to call `make dist` from cargo.

I don't plan on moving away from the "git tags" approach. Because it brings together version with the digest of source code, including  ["signed tags"](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work).

Currently `make dist` requires GNU versions of make, sed, and bash, but this is a minor flaw and I'm not sure if it should be fixed.

P.S.
Thank you for Rust bindings.

**Comment by Kerollmops** [comment]
Hey,

I have made some experiments with the `make dist` rule on macos and it seems like some `tar` options are not supported on this OS.

I achieved to make it work by removing the `--owner=0`, and `--group=0`. The order of the options were also a problem so moved the `-f -` options at the front of the command. After these changes the build worked and a `dist/` folder is available.

```diff
- tar -c --owner=0 --group=0 -C dist $(DIST_SRC) $(DIST_EXTRA) -f - | gzip -c > $@ \
+ tar -c -f - -C dist $(DIST_SRC) $(DIST_EXTRA) | gzip -c > $@ \
```

```
drwxr-xr-x    - clementrenault 31 mar 10:45 -- dist
.rw-r--r-- 9,8k clementrenault 31 mar 10:44 -- ├── CMakeLists.txt
.rw-r--r-- 5,6k clementrenault 31 mar 10:45 -- ├── GNUmakefile
.rw-r--r-- 2,2k clementrenault 31 mar 10:44 -- ├── LICENSE
.rw-r--r--  458 clementrenault 31 mar 10:44 -- ├── Makefile
drwxr-xr-x    - clementrenault 31 mar 10:44 -- ├── man1
.rw-r--r-- 2,6k clementrenault 31 mar 10:44 -- │  ├── mdbx_chk.1
.rw-r--r-- 1,8k clementrenault 31 mar 10:44 -- │  ├── mdbx_copy.1
.rw-r--r-- 2,5k clementrenault 31 mar 10:44 -- │  ├── mdbx_dump.1
.rw-r--r-- 3,0k clementrenault 31 mar 10:44 -- │  ├── mdbx_load.1
.rw-r--r-- 2,0k clementrenault 31 mar 10:44 -- │  └── mdbx_stat.1
.rw-r--r-- 918k clementrenault 31 mar 10:45 -- ├── mdbx.c
.rw-r--r-- 177k clementrenault 31 mar 10:45 -- ├── mdbx.h
.rw-r--r-- 159k clementrenault 31 mar 10:45 -- ├── mdbx_chk.c
.rw-r--r-- 115k clementrenault 31 mar 10:45 -- ├── mdbx_copy.c
.rw-r--r-- 121k clementrenault 31 mar 10:45 -- ├── mdbx_dump.c
.rw-r--r-- 128k clementrenault 31 mar 10:45 -- ├── mdbx_load.c
.rw-r--r-- 125k clementrenault 31 mar 10:45 -- ├── mdbx_stat.c
.rw-r--r--  27k clementrenault 31 mar 10:44 -- └── README.md
```

I will try to improve the Rust wrapper and make it work on all platforms by using this almagated source code. I also saw that you created an issue to expose this almagated folder in the assets in every releases, that's a good thing I think :)

**Comment by Kerollmops** [comment]
Hey @erthink,

I have finally made it work really easily, the Rust crate do not depend on a git submodule but only on a raw copy of the generated dist folder.

I just have specified some correctness flags to gcc and some warnings popped up, do you think they are relevant at all?

```
warning: /.../mdbx-rs/mdbx-sys/libmdbx/mdbx.c:1213:18: warning: cast from function call of type 'pthread_t _Nonnull' (aka 'struct _opaque_pthread_t *') to non-matching type 'size_t' (aka 'unsigned long') [-Wbad-function-cast]
warning:   return (size_t)pthread_self();
warning:                  ^~~~~~~~~~~~~~
warning: /.../mdbx-rs/mdbx-sys/libmdbx/mdbx.c:21156:1: warning: missing field 'flags' initializer [-Wmissing-field-initializers]
warning: };
warning: ^
warning: 2 warnings generated.
```

**Comment by erthink** [comment]
These warnings are not dangerous, but they should still be fixed. Please create an issue.
