### ISSUE TITLE
Proofreading API description and README by native English speaker

### ISSUE THREAD

**Issue by erthink** [erthink/libmdbx#87]
There are two items:
1. API description inside the [mdbx.h](https://github.com/erthink/libmdbx/blob/master/mdbx.h)
2. The [README.md](https://github.com/erthink/libmdbx/blob/master/README.md)

[PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) are welcome!

**Comment by zachgrayio** [comment]
Hi there @erthink , I'd be happy to help with this. Not an expert on the codebase yet, but we do make use of this library in one of our projects--thank you by the way, amazing work here.

**Comment by jsoref** [comment]
In the interim, you could try feeding either document to https://app.grammarly.com/ -- I do that occasionally. It won't result in a perfect document, but it will on average significantly improve things.

**Comment by erthink** [comment]
Seems obsolete.
