### ISSUE TITLE
Windows MSVC 2017 build fails [master]

### ISSUE THREAD

**Issue by oleg-kiriyenko** [erthink/libmdbx#96]
When built on Windows I get error on redifinition of mode_t

#include <windows.h>
#include <winnt.h>
#ifndef __mode_t_defined
typedef unsigned short mode_t;
#endif

{
	"resource": "libmdbx/mdbx.h",
	"owner": "cmake-build-diags",
	"code": "C2371",
	"severity": 8,
	"message": "'mode_t': redefinition; different basic types",
	"source": "MSVC",
	"startLineNumber": 559,
	"startColumn": 1,
	"endLineNumber": 559,
	"endColumn": 1000
}

**Comment by oleg-kiriyenko** [comment]
Was my mistake. It was already defined one header above.

**Comment by erthink** [comment]
The `mode_t` is nowhere defined inside MSVC-2013/2015/2017/2019 toolchain or Windows SDK, except cross-compilation for Linux but with providing the `__mode_t_defined` guard.

If you use `mdbx.h` with some other header files which are defines `mode_t`, then the error is that `__mode_t_defined` is not defined there. So you should submit issue "`mode_t` defined without `__mode_t_defined`" to the corresponding projects (but not here) or just add `__mode_t_defined` definition into your code manually.

Тем не менее, если в каких-то заголовочных файлов вместо `__mode_t_defined` используется еще какой-то макрос, то я готов его добавить (либо просто оформите PR).
